version: '3'

services:
    web:
        image: 'nginx:latest'
        restart: 'on-failure'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./logs:/var/log/nginx
            - ./app:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - lemp
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        restart: 'on-failure'
        ports:
            - '9000:9000'
        volumes:
            - ./app:/app
        networks:
            - lemp
    db:
        image: 'mysql:5.7.24'
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db-data:/var/lib/mysql
            - ./db-dumps:/docker-entrypoint-initdb.d

        restart: 'on-failure'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - '3306:3306'

        networks:
            - lemp

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        ports:
            - '8080:80'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_HOST: db
        links:
            - db
        networks:
            - lemp

networks:
    lemp:
